---
title: "DACSS 695 FINAL"
author: "Emerson Fleming"
date: "5/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(dplyr)
library(ggcorrplot)
library(hrbrthemes)
library(ggpubr)
```


```{r}
Financial_Lit_Data <- read_csv("./EFleming DACSS 695 Final Project Dataset (Mark II) - Sheet1 (1).csv")
```

```{r}
Financial_Model <- lm(Financial_Literacy_Strictness~Percent_Republican + Percent_Democrat + Minority_Percentage + Median_Income, data = Financial_Lit_Data)
summary(Financial_Model)
```


```{r}
Financial_Lit_Cor <- select(Financial_Lit_Data, Financial_Literacy_Strictness, Percent_Republican, Percent_Democrat, Percent_Independent, Minority_Percentage, Median_Income)
```

```{r}
Financial_Lit_Cor_Graph_Data <- cor(Financial_Lit_Cor)
cor(Financial_Lit_Cor)
```

```{r}
ggcorrplot(Financial_Lit_Cor_Graph_Data, lab = TRUE, hc.order = TRUE, ggtheme = ggplot2::theme_minimal())
```


## Graphical Demonstration of Correlation Coefficients
```{r}
ggcorrplot(Financial_Lit_Cor_Graph_Data, lab = TRUE, hc.order = TRUE, ggtheme = ggplot2::theme_minimal())
```


## Graphical Demonstration of P-Values
```{r}
Financial_Lit_P_Cor <- cor_pmat(Financial_Lit_Cor) 
ggcorrplot(Financial_Lit_P_Cor, lab = TRUE, hc.order = TRUE, ggtheme = ggplot2::theme_minimal())
```


```{r}
q1 <- ggplot(Financial_Model,
  aes(x = Financial_Literacy_Strictness, y = Percent_Democrat)) +
  geom_line(color = "black") +
  geom_smooth(color = "blue") +
  coord_cartesian(xlim = c(0, 4), ylim = c(0, 100)) +
labs(caption = "Source: Pew Research Center & CFEE",
       x = "Financial Literacy Strictness",
       y = "Percentage Democrat") +
theme_ipsum() +
theme(plot.title = element_text(size=15))
```

```{r}
q2 <- ggplot(Financial_Model,
  aes(x = Financial_Literacy_Strictness, y = Percent_Republican)) +
  geom_line(color = "black") +
  geom_smooth(color = "red") +
  coord_cartesian(xlim = c(0, 4), ylim = c(0, 100)) +
labs(caption = "Source: Pew Research Center & CFEE",
       x = "Financial Literacy Strictness",
       y = "Percentage Republican") +
theme_ipsum() +
theme(plot.title = element_text(size=15))
```

```{r}
q3 <- ggplot(Financial_Model,
  aes(x = Financial_Literacy_Strictness, y = Minority_Percentage)) +
  geom_line(color = "black") +
  geom_smooth(color = "green") +
  coord_cartesian(xlim = c(0, 4), ylim = c(0, 50)) +
labs(caption = "Source: World Population Review",
       x = "Financial Literacy Strictness",
       y = "Minority Percentage") +
theme_ipsum() +
theme(plot.title = element_text(size=15))
```

```{r}
q4 <- ggplot(Financial_Model,
  aes(x = Financial_Literacy_Strictness, y = Median_Income)) +
  geom_line(color = "black") +
  geom_smooth(color = "yellow") +
  coord_cartesian(xlim = c(0, 4), ylim = c(0, 100)) +
labs(caption = "Source: St. Louis Fed",
       x = "Financial Literacy Strictness",
       y = "Median Income") +
theme_ipsum() +
theme(plot.title = element_text(size=15))
```

```{r}
plot <- ggarrange(q1, q2, ncol=2, nrow=1, common.legend = TRUE,legend="bottom")
annotate_figure(plot, top = text_grob("Financial Literacy Strictness vs. Partisanship", 
               color = "Black", face = "bold", size = 14))
ggsave()
```

```{r}
plot <- ggarrange(q3, q4, ncol=2, nrow=1, common.legend = TRUE,legend="bottom")
annotate_figure(plot, top = text_grob("Financial Literacy Strictness vs. Minority Percentage & Median Income", 
               color = "Black", face = "bold", size = 14))
```
